Update Project to Qt 6
OSSystems/qt-kiosk-browser pull request #13
Opened 2023-10-05 19:49 UTC by arthursdo

This PR updates the project from Qt 5 to Qt 6. The changes made include:

1. **browser.pro**: Updated the Qt modules used in the project. The following changes were made:
   - Removed: `webengine` and `webenginewidgets`
   - Added: `webenginequick` and `widgets`

2. **main.cpp**: Adjusted the Qt includes and initialization for Qt 6. The following changes were made:
   - Updated includes to use Qt 6 headers.
   - Added application name with `QCoreApplication::setApplicationName`.
   - Set environment variables `QT_IM_MODULE` and `QML_XHR_ALLOW_FILE_READ`.
   - Initialized QtWebEngineQuick with `QtWebEngineQuick::initialize`.

These changes ensure compatibility with Qt 6 and update the project accordingly.

2023-10-05 20:02 UTC, otavio requested changes

2023-10-05 20:02 UTC, otavio commented on main.cpp
> +}
newline pls

2023-10-05 20:02 UTC, otavio commented on qml/main.qml
> +
empty spaces, please remove

2023-10-05 21:53 UTC, otavio approved these changes

2023-10-05 21:53 UTC, merged

2024-03-13 07:38 UTC, Jarred-Wynan commented
Is there a roadmap for adding this project as a yocto supported layer? We are very interested in utilising the functions provided here in a version that is compatible with Qt6.